### ISSUE TITLE
Invalid Bytes sequence..

### ISSUE THREAD

**Issue by simonprovost** [ronanboiteau/NormEZ#1] opened 2018-01-25 22:12 UTC
> NormEZ.rb:293:in 'block in check_trailing_spaces_tabs': invalid byte sequence in UTF-8 (ArgumentError)
>         from NormEZ.rb:292:in 'each_line'
>         from NormEZ.rb:292:in 'check_trailing_spaces_tabs'
>         from NormEZ.rb:126:in 'check_file'
>         from NormEZ.rb:122:in 'initialize'
>         from NormEZ.rb:542:in 'new'
>         from NormEZ.rb:542:in '\<main\>'

What is it?

**Comment by ronanboiteau** [comment] 2018-01-25 22:20
NormEZ has not been tested for UTF-8. Can you create a zip or tar archive with the repository you're analyzing & post it here? Or, if you don't want to post your code here, you can e-mail it to me at ronan.boiteau@epitech.eu. I'll try to reproduce this bug & push a fix.

**Comment by ronanboiteau** [comment] 2018-01-28 21:07
Seems like there was a bug in file extension detection. I just pushed a fix. Can you tell me if it is working now?

**Closed as completed** 2018-02-02 15:40 UTC
Labels: bug

**Comment by ronanboiteau** [comment] 2018-02-02 15:41
Bug fixed since commit [0a929fdf7aee92763f242aca02c717de5edfe1df](https://github.com/ronanboiteau/NormEZ/commit/0a929fdf7aee92763f242aca02c717de5edfe1df).
